// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, type) VALUES ($1, $2) RETURNING id
`

type CreateAccountParams struct {
	Name string      `json:"name"`
	Type AccountType `json:"type"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Name, arg.Type)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (account_id, transaction_id, credit, debit) VALUES ($1, $2, $3, $4) returning id
`

type CreateEntryParams struct {
	AccountID     uuid.UUID `json:"account_id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	Credit        string    `json:"credit"`
	Debit         string    `json:"debit"`
}

// Ensure to call UpdateAccountBalance after this to maintain consistency
func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.AccountID,
		arg.TransactionID,
		arg.Credit,
		arg.Debit,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions DEFAULT VALUES RETURNING id
`

func (q *Queries) CreateTransaction(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createTransaction)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT CASE
    WHEN type IN ('asset', 'expense') THEN accounts.balance
    ELSE accounts.balance * -1
END AS balance
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountBalance(ctx context.Context, id uuid.UUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalance, id)
	var balance interface{}
	err := row.Scan(&balance)
	return balance, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET balance = balance + $2 - $3
WHERE id = $1
RETURNING balance
`

type UpdateAccountBalanceParams struct {
	ID        uuid.UUID `json:"id"`
	Balance   string    `json:"balance"`
	Balance_2 string    `json:"balance_2"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (string, error) {
	row := q.db.QueryRowContext(ctx, updateAccountBalance, arg.ID, arg.Balance, arg.Balance_2)
	var balance string
	err := row.Scan(&balance)
	return balance, err
}
