// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO idempotency_keys (key, request_checksum, status)
VALUES ($1, $2, 'processing')
ON CONFLICT (key) DO UPDATE
SET updated_at = NOW()
RETURNING transaction_id, request_checksum, status
`

type ClaimIdempotencyKeyParams struct {
	Key             string `json:"key"`
	RequestChecksum string `json:"request_checksum"`
}

type ClaimIdempotencyKeyRow struct {
	TransactionID   uuid.NullUUID `json:"transaction_id"`
	RequestChecksum string        `json:"request_checksum"`
	Status          string        `json:"status"`
}

func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (ClaimIdempotencyKeyRow, error) {
	row := q.db.QueryRowContext(ctx, claimIdempotencyKey, arg.Key, arg.RequestChecksum)
	var i ClaimIdempotencyKeyRow
	err := row.Scan(&i.TransactionID, &i.RequestChecksum, &i.Status)
	return i, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET transaction_id = $2, status = 'completed', updated_at = NOW()
WHERE key = $1
`

type CompleteIdempotencyKeyParams struct {
	Key           string        `json:"key"`
	TransactionID uuid.NullUUID `json:"transaction_id"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.ExecContext(ctx, completeIdempotencyKey, arg.Key, arg.TransactionID)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, type) VALUES ($1, $2) RETURNING id
`

type CreateAccountParams struct {
	Name string      `json:"name"`
	Type AccountType `json:"type"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Name, arg.Type)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (account_id, transaction_id, credit, debit) VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateEntryParams struct {
	AccountID     uuid.UUID `json:"account_id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	Credit        string    `json:"credit"`
	Debit         string    `json:"debit"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.AccountID,
		arg.TransactionID,
		arg.Credit,
		arg.Debit,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions DEFAULT VALUES RETURNING id
`

func (q *Queries) CreateTransaction(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createTransaction)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT CAST(CASE
    WHEN type IN ('asset', 'expense') THEN balance
    ELSE balance * -1
END AS NUMERIC(20,2)) AS balance
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountBalance(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalance, id)
	var balance string
	err := row.Scan(&balance)
	return balance, err
}

const getAccountEntries = `-- name: GetAccountEntries :many
SELECT id, account_id, transaction_id, credit, debit, created_at
FROM entries
WHERE account_id = $1 AND created_at >= $2 AND created_at <= $3
ORDER BY created_at ASC, id ASC
`

type GetAccountEntriesParams struct {
	AccountID   uuid.UUID `json:"account_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) GetAccountEntries(ctx context.Context, arg GetAccountEntriesParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getAccountEntries, arg.AccountID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionID,
			&i.Credit,
			&i.Debit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntriesByTransactionID = `-- name: GetEntriesByTransactionID :many
SELECT id, account_id, transaction_id, credit, debit, created_at
FROM entries
WHERE transaction_id = $1
`

func (q *Queries) GetEntriesByTransactionID(ctx context.Context, transactionID uuid.UUID) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getEntriesByTransactionID, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionID,
			&i.Credit,
			&i.Debit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET balance = balance + $2 - $3
WHERE id = $1
RETURNING balance
`

type UpdateAccountBalanceParams struct {
	ID        uuid.UUID `json:"id"`
	Balance   string    `json:"balance"`
	Balance_2 string    `json:"balance_2"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (string, error) {
	row := q.db.QueryRowContext(ctx, updateAccountBalance, arg.ID, arg.Balance, arg.Balance_2)
	var balance string
	err := row.Scan(&balance)
	return balance, err
}
